name: Build and Deploy
on:
  push:
    branches:
      - ele-v1.0
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build ğŸ”§
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

  prune-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Prune Cache ğŸ§¹
        run: |
          npm install -g pnpm
          pnpm store prune

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-deploy, prune-cache]  # This ensures that "deploy" runs after both "build-and-deploy" and "prune-cache" jobs.
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN  }}
          BRANCH: gh-pages
          FOLDER: dist
